# Week 08: Phrase Classification
The assignment this week needs you to distinguish between good and bad phrases of the word "**earn**" (e.g., earn money). The method, word2vector, learned today will be used in the process. 

There're some data for this assignment: 
* train.tsv: Some phrases with labels to train and validate the classification model. There are only two types of label: 1 means *good*; 0 means *bad*.
* test.tsv: Same format as train.tsv. It's used to test your model.
* GoogleNews-vectors-negative300.bin.gz: a pre-trained word2vector model trained by Google ([source](https://code.google.com/archive/p/word2vec/))

## Requirement
* pandas
* tensorflow
* sklearn

## Read Data
We use dataframe to store data here.

In [1]:
import pandas as pd
def loadData(path):
    ngram = []
    _class = []
    with open(path, encoding='utf8') as f:
        for line in f.readlines():
            line = line.strip("\n").split("\t")
            ngram.append(line[0])
            _class.append(int(line[1]))
    return pd.DataFrame({"phrase":ngram,"class":_class})
train = loadData("train.tsv")
print(train.head())
test = loadData("test.tsv")    
print(test.head())

                         phrase  class
0      earn a strong reputation      1
1  Marty will surely earn every      0
2             to earn between $      0
3          to earn some college      0
4        that earn rave reviews      0
                   phrase  class
0  degree earn 62 percent      0
1     earn maybe 30 or 50      0
2  earn the kind of money      1
3      earn his 14th save      1
4   earn a smaller amount      1


## load word2vec model
<font color="red">**[ TODO ]**</font> Please load [GoogleNews-vectors-negative300.bin.gz](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?resourcekey=0-wjGZdNAUop6WykTtMip30g) model and check the embedding of the word `language`.

* package `gensim` is a good choice

In [2]:
import gensim
from gensim import models

w = models.KeyedVectors.load_word2vec_format(
    'GoogleNews-vectors-negative300.bin', binary=True)
#### print "language" embedding 
w['language']

array([ 2.30712891e-02,  1.68457031e-02,  1.54296875e-01,  1.27929688e-01,
       -2.67578125e-01,  3.51562500e-02,  1.19140625e-01,  2.48046875e-01,
        1.93359375e-01, -7.95898438e-02,  1.46484375e-01, -1.43554688e-01,
       -3.04687500e-01,  3.46679688e-02, -1.85546875e-02,  1.06933594e-01,
       -1.52343750e-01,  2.89062500e-01,  2.35595703e-02, -3.80859375e-01,
        1.09863281e-01,  4.41406250e-01,  3.75976562e-02, -1.22680664e-02,
        1.62353516e-02, -2.24609375e-01,  7.61718750e-02, -3.12500000e-02,
       -2.16064453e-02,  1.49414062e-01, -4.02832031e-02, -4.46777344e-02,
       -1.72851562e-01,  3.32031250e-02,  1.50390625e-01, -5.05371094e-02,
        2.72216797e-02,  3.00781250e-01, -1.33789062e-01, -7.56835938e-02,
        1.93359375e-01, -1.98242188e-01, -1.27563477e-02,  4.19921875e-01,
       -2.19726562e-01,  1.44531250e-01, -3.93066406e-02,  1.94335938e-01,
       -3.12500000e-01,  1.84570312e-01,  1.48773193e-04, -1.67968750e-01,
       -7.37304688e-02, -

<font color="green">Expected output: </font>

>  <font face='monospace' size=3>\[&nbsp;2.30712891e-02&nbsp;&nbsp;1.68457031e-02&nbsp;&nbsp;1.54296875e-01&nbsp; 1.27929688e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.67578125e-01&nbsp;&nbsp;3.51562500e-02&nbsp;&nbsp;1.19140625e-01&nbsp; 2.48046875e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.93359375e-01&nbsp;-7.95898438e-02&nbsp;&nbsp;1.46484375e-01&nbsp;-1.43554688e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-3.04687500e-01&nbsp;&nbsp;3.46679688e-02&nbsp;-1.85546875e-02&nbsp; 1.06933594e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.52343750e-01&nbsp;&nbsp;2.89062500e-01&nbsp;&nbsp;2.35595703e-02&nbsp;-3.80859375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.09863281e-01&nbsp;&nbsp;4.41406250e-01&nbsp;&nbsp;3.75976562e-02&nbsp;-1.22680664e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.62353516e-02&nbsp;-2.24609375e-01&nbsp;&nbsp;7.61718750e-02&nbsp;-3.12500000e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.16064453e-02&nbsp;&nbsp;1.49414062e-01&nbsp;-4.02832031e-02&nbsp;-4.46777344e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.72851562e-01&nbsp;&nbsp;3.32031250e-02&nbsp;&nbsp;1.50390625e-01&nbsp;-5.05371094e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.72216797e-02&nbsp;&nbsp;3.00781250e-01&nbsp;-1.33789062e-01&nbsp;-7.56835938e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.93359375e-01&nbsp;-1.98242188e-01&nbsp;-1.27563477e-02&nbsp; 4.19921875e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.19726562e-01&nbsp;&nbsp;1.44531250e-01&nbsp;-3.93066406e-02&nbsp; 1.94335938e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-3.12500000e-01&nbsp;&nbsp;1.84570312e-01&nbsp;&nbsp;1.48773193e-04&nbsp;-1.67968750e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-7.37304688e-02&nbsp;-3.12500000e-02&nbsp;&nbsp;1.57226562e-01&nbsp; 3.30078125e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.42578125e-01&nbsp;-3.16406250e-01&nbsp;-7.32421875e-02&nbsp;-5.76171875e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.02050781e-01&nbsp;-1.08886719e-01&nbsp;&nbsp;1.24023438e-01&nbsp;-2.50244141e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.49023438e-01&nbsp;&nbsp;1.25976562e-01&nbsp;-1.79687500e-01&nbsp; 3.32031250e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;7.14111328e-03&nbsp;&nbsp;2.51953125e-01&nbsp;&nbsp;4.34570312e-02&nbsp;-4.34570312e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-3.90625000e-01&nbsp;&nbsp;1.76757812e-01&nbsp;-1.13525391e-02&nbsp;-1.97753906e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.79296875e-01&nbsp;&nbsp;2.36328125e-01&nbsp;&nbsp;1.19140625e-01&nbsp; 5.59082031e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.73828125e-01&nbsp;-1.10839844e-01&nbsp;-4.95605469e-02&nbsp; 2.13867188e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;6.17675781e-02&nbsp;&nbsp;1.38671875e-01&nbsp;-4.45556641e-03&nbsp; 2.55859375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.80664062e-01&nbsp;&nbsp;5.88378906e-02&nbsp;-6.59179688e-02&nbsp;-2.08007812e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.19140625e-01&nbsp;-1.57226562e-01&nbsp;&nbsp;5.02929688e-02&nbsp;-6.29882812e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;5.00488281e-02&nbsp;-7.27539062e-02&nbsp;&nbsp;1.74560547e-02&nbsp;-3.56445312e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.93359375e-01&nbsp;&nbsp;3.93066406e-02&nbsp;-3.36914062e-02&nbsp;-1.07421875e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;5.78613281e-02&nbsp;-8.20312500e-02&nbsp;&nbsp;1.74560547e-02&nbsp;-1.65039062e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.46484375e-01&nbsp;-3.08837891e-02&nbsp;-3.86718750e-01&nbsp; 2.49023438e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;8.74023438e-02&nbsp;-2.15820312e-01&nbsp;-4.10156250e-02&nbsp; 1.60156250e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.85546875e-01&nbsp;-2.27050781e-02&nbsp;-3.73535156e-02&nbsp; 7.86132812e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.46484375e-01&nbsp;&nbsp;6.78710938e-02&nbsp;&nbsp;1.26953125e-01&nbsp; 3.30078125e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.11328125e-01&nbsp;&nbsp;9.27734375e-02&nbsp;-3.45703125e-01&nbsp;-1.41601562e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-5.29785156e-02&nbsp;-1.50390625e-01&nbsp;-7.81250000e-02&nbsp;-1.27929688e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-4.02343750e-01&nbsp;-1.41601562e-01&nbsp;&nbsp;8.44726562e-02&nbsp; 1.08398438e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-4.44335938e-02&nbsp;&nbsp;3.73535156e-02&nbsp;&nbsp;5.61523438e-02&nbsp;-1.91406250e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.54296875e-01&nbsp;-5.12695312e-02&nbsp;-6.49414062e-02&nbsp;-8.30078125e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;7.17773438e-02&nbsp;-1.33789062e-01&nbsp;&nbsp;1.05468750e-01&nbsp; 3.33984375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.08398438e-01&nbsp;&nbsp;1.91650391e-02&nbsp;&nbsp;2.14843750e-01&nbsp; 2.15820312e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.05468750e-01&nbsp;-1.44531250e-01&nbsp;&nbsp;4.32128906e-02&nbsp;-2.71484375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-3.78906250e-01&nbsp;&nbsp;1.09863281e-01&nbsp;-8.15429688e-02&nbsp;-6.12792969e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.33789062e-01&nbsp;&nbsp;9.71679688e-02&nbsp;-1.04370117e-02&nbsp;-1.21093750e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.44140625e-01&nbsp;&nbsp;1.02050781e-01&nbsp;&nbsp;1.10839844e-01&nbsp;-1.00585938e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.71875000e-01&nbsp;-3.61328125e-02&nbsp;-4.39453125e-02&nbsp; 2.83203125e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-8.93554688e-02&nbsp;-1.70898438e-01&nbsp;&nbsp;2.46093750e-01&nbsp; 1.16699219e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;8.39843750e-02&nbsp;-1.32812500e-01&nbsp;-1.61132812e-01&nbsp;-1.39648438e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-8.59375000e-02&nbsp;-1.37695312e-01&nbsp;-9.32617188e-02&nbsp;-1.33789062e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.65039062e-01&nbsp;&nbsp;4.93164062e-02&nbsp;-1.21093750e-01&nbsp;-2.11914062e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;1.61132812e-01&nbsp;-1.07421875e-01&nbsp;-3.97949219e-02&nbsp;-3.51562500e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-5.02929688e-02&nbsp;&nbsp;1.46484375e-01&nbsp;-4.68750000e-02&nbsp; 4.17480469e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.27929688e-01&nbsp;-9.76562500e-02&nbsp;-2.46093750e-01&nbsp; 6.78710938e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.30468750e-01&nbsp;&nbsp;1.80664062e-02&nbsp;&nbsp;3.54003906e-02&nbsp; 7.32421875e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.23632812e-01&nbsp;-1.25976562e-01&nbsp;&nbsp;2.12890625e-01&nbsp;-3.93066406e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.41699219e-02&nbsp;-9.61914062e-02&nbsp;&nbsp;7.51953125e-02&nbsp;-1.46484375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.49414062e-01&nbsp;-8.83789062e-02&nbsp;-4.88281250e-02&nbsp; 2.32421875e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;3.30078125e-01&nbsp;&nbsp;1.59179688e-01&nbsp;-2.35351562e-01&nbsp;-1.25976562e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.68554688e-02&nbsp;-5.29785156e-02&nbsp;-6.59179688e-02&nbsp;-2.17773438e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-6.37817383e-03&nbsp;-2.53906250e-01&nbsp;&nbsp;2.28515625e-01&nbsp; 4.93164062e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;3.54003906e-02&nbsp;&nbsp;1.66992188e-01&nbsp;-7.27539062e-02&nbsp;-2.53906250e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.34765625e-01&nbsp;&nbsp;3.69140625e-01&nbsp;&nbsp;1.83593750e-01&nbsp;-1.64062500e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.26562500e-01&nbsp;-8.88671875e-02&nbsp;&nbsp;3.69140625e-01&nbsp; 5.54199219e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-3.63769531e-02&nbsp;-1.48437500e-01&nbsp;&nbsp;9.13085938e-02&nbsp; 2.47955322e-04<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.67578125e-01&nbsp;-1.63085938e-01&nbsp;&nbsp;1.19628906e-01&nbsp; 2.77343750e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.49414062e-01&nbsp;&nbsp;1.33789062e-01&nbsp;-8.25195312e-02&nbsp;-1.74804688e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.77734375e-01&nbsp;&nbsp;2.06054688e-01&nbsp;&nbsp;5.07812500e-02&nbsp;-2.08007812e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.74804688e-01&nbsp;&nbsp;9.66796875e-02&nbsp;&nbsp;6.98242188e-02&nbsp;-5.79833984e-04<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;9.22851562e-02&nbsp;&nbsp;7.95898438e-02&nbsp;&nbsp;1.41601562e-01&nbsp; 8.72802734e-03<br> </font>
>  <font face='monospace' size=3>&nbsp;-8.05664062e-02&nbsp;&nbsp;4.80957031e-02&nbsp;&nbsp;2.49023438e-01&nbsp;-1.64062500e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-4.66308594e-02&nbsp;-2.81250000e-01&nbsp;-1.66015625e-01&nbsp;-2.22656250e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-2.32421875e-01&nbsp;&nbsp;1.32812500e-01&nbsp;&nbsp;4.15039062e-02&nbsp; 1.15234375e-01<br> </font>
>  <font face='monospace' size=3>&nbsp;-7.66601562e-02&nbsp;-1.10839844e-01&nbsp;-1.97265625e-01&nbsp; 3.06396484e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.03515625e-01&nbsp;&nbsp;2.49023438e-02&nbsp;-2.52685547e-02&nbsp; 3.39355469e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;4.29687500e-02&nbsp;-1.44531250e-01&nbsp;&nbsp;2.12402344e-02&nbsp; 2.28271484e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.88476562e-01&nbsp;&nbsp;3.22265625e-01&nbsp;-1.13281250e-01&nbsp;-7.61718750e-02<br> </font>
>  <font face='monospace' size=3>&nbsp;&nbsp;2.94921875e-01&nbsp;-1.33789062e-01&nbsp;-1.80664062e-02&nbsp;-6.25610352e-03<br> </font>
>  <font face='monospace' size=3>&nbsp;-1.62353516e-02&nbsp;&nbsp;5.98144531e-02&nbsp;&nbsp;1.21582031e-01&nbsp; 4.17480469e-02\] </font>

## Preprocessing
Preprocess two tsv files here.

#### adjust the ratio of the two classes of training data
In training data, the ratio of good phrases to bad phrases is about one to thirty. That will make training classification unsatisfactory, so we need to adjust the ratio. Reducing bad phrases and adding good phrases are both common way.

<font color="red">**[ TODO ]**</font> Please adjust the ratio of good phrases to bad phrases in any way which you think is the best and output the number of two class for demo.

You need to explain why you choose this ratio and how you do it.

可以增加好片語的資料量，來提升比例。

或減少壞片語的量。

輸出兩類的筆數

In [3]:
from sklearn.utils import shuffle
total_train = train[train['class']==1].append(train[train['class']==0].sample(6105, random_state=1))
total_train = shuffle(total_train)
train = total_train

print(train[train['class']==1].count())
print(train[train['class']==0].count())

phrase    6105
class     6105
dtype: int64
phrase    6105
class     6105
dtype: int64


#### number words
Let each word have its unique number.

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tok = Tokenizer()
tok.fit_on_texts(pd.concat([train,test],ignore_index=True)['phrase'])
vocab_size = len(tok.word_index) + 1

#tok.word_index: 為 dictionary

#### convert phrases into numbers
Because model can't read words, so we have to do this transform. 

The number should be same as the last step.

In [5]:
train_encoded_phrase = tok.texts_to_sequences(train['phrase'])
test_encoded_phrase = tok.texts_to_sequences(test['phrase'])

#### padding
Make all phrases become same length. The longest phrases in two tsv have five tokens. Hence, we should make the phrases whose lengths less than five become five by adding 0. 

In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_ngram = 5
X_train= pad_sequences(train_encoded_phrase, maxlen=max_ngram, padding='post')
X_test= pad_sequences(test_encoded_phrase, maxlen=max_ngram, padding='post')
print(X_train[:5])

[[  14    1 1167  189 1680]
 [   1    5   96    4    0]
 [   1   27   36    0    0]
 [   1  102  136  775   17]
 [   7  126    2    1  378]]


In [20]:
train['class'][0:5]

31395     0
17702     0
70089     1
197406    0
124297    0
Name: class, dtype: int64

#### one hot encodding label

In [8]:
from tensorflow.keras.utils import to_categorical
y_train=to_categorical(train['class'])
y_test=to_categorical(test['class'])
print(y_train[:5])

# 前面一項代表 '0', 後面一項代表 '1'

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


#### split training data into train and validation

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train,test_size=0.20,random_state=42)

#### creating the embedding matrix
The embedding matrix is used by classification model. It should be a list of list. Each sub-list is an embedding vector of a word and the order of all embedding vectors should be same as *tokenizer*. It is stored in a dictionary. You can check it by `tok.word_index()`.

<font color="red">**[ TODO ]**</font> Make embedding matrix. If you don't need it for your classification model, you can skip it. We won't check it when demo. 

- [Keras—embedding嵌入層的用法詳解](https://www.796t.com/article.php?id=22887) 包含 embedding matrix 作法

**The embedding matrix will always have the number of columns equal to the number of the embedding dimension and the row count will be equal to the number of unique words in the document or a user-defined number of rows.**

In [10]:
import numpy as np
dim = 300
embedding_matrix = np.zeros((vocab_size, dim))

for word, i in tok.word_index.items():
    try:
        embedding_vec = w[word]
        if embedding_vec is not None:
            embedding_matrix[i] = embedding_vec
    except KeyError:
        continue

## Classification

#### build model
<font color="red">**[ TODO ]**</font> Please build your classification model by ***keras*** here. 

You **must** use the pre-trained word2vec model to represent the words of phrases.

推薦使用 LSTM

- [Day 05：Keras 模型、函數及參數使用說明](https://ithelp.ithome.com.tw/articles/10191725)

How to embedding initialize with `embedding matrix`? 

- [How to use a pre-trained embedding matrix in tensorflow 2.0 RNN as initial weights in an embedding layer?](https://stackoverflow.com/questions/55770009/how-to-use-a-pre-trained-embedding-matrix-in-tensorflow-2-0-rnn-as-initial-weigh)

In [11]:
import tensorflow as tf
from tensorflow import keras
model = tf.keras.models.Sequential([
    # Embedding layer 只能加在第一層, 且透過 `embedding_initializer` 來利用 embedding_matrix 來初始化
    tf.keras.layers.Embedding(vocab_size, dim, input_length = 5, embeddings_initializer=keras.initializers.constant(embedding_matrix)),

    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.Dropout(0.52),  
    tf.keras.layers.LSTM(64, return_sequences=True),
    tf.keras.layers.Dropout(0.41),  

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [12]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 300)            979500    
_________________________________________________________________
lstm (LSTM)                  (None, 5, 128)            219648    
_________________________________________________________________
dropout (Dropout)            (None, 5, 128)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 5, 64)             49408     
_________________________________________________________________
dropout_1 (Dropout)          (None, 5, 64)             0         
_________________________________________________________________
flatten (Flatten)            (None, 320)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 320)               0

#### train
Train classification model here.

<font color="red">**[ TODO ]**</font> Adjust the hyperparameter to optimize the validation accuracy and validation loss.

* The higher the accuracy, the better; the lower the validation, the better.
* **number of epoch** and **batch size** are the most important

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train,y_train,validation_data=(X_val,y_val), epochs=20, batch_size=1000)

Epoch 1/20
10/10 [==============================] - 5s 217ms/step - loss: 0.6084 - accuracy: 0.6732 - val_loss: 0.6643 - val_accuracy: 0.7584
Epoch 2/20
10/10 [==============================] - 1s 146ms/step - loss: 0.3983 - accuracy: 0.8257 - val_loss: 0.6130 - val_accuracy: 0.7445
Epoch 3/20
10/10 [==============================] - 2s 151ms/step - loss: 0.2999 - accuracy: 0.8738 - val_loss: 0.5892 - val_accuracy: 0.7019
Epoch 4/20
10/10 [==============================] - 1s 148ms/step - loss: 0.2399 - accuracy: 0.9092 - val_loss: 0.5623 - val_accuracy: 0.7207
Epoch 5/20
10/10 [==============================] - 1s 147ms/step - loss: 0.1882 - accuracy: 0.9326 - val_loss: 0.5261 - val_accuracy: 0.7625
Epoch 6/20
10/10 [==============================] - 2s 195ms/step - loss: 0.1512 - accuracy: 0.9475 - val_loss: 0.5038 - val_accuracy: 0.7432
Epoch 7/20
10/10 [==============================] - 2s 161ms/step - loss: 0.1220 - accuracy: 0.9587 - val_loss: 0.4723 - val_accuracy: 0.7678
Epoch 

#### test

<font color="red">**[ TODO ]**</font> Test your model by test.tsv and output the accuracy. Your accuracy need to beat baseline: **0.97**.

In [14]:
# Keras中 model.evaluate（）返回的是 损失值和你选定的指标值（例如，精度accuracy）
accuracy = model.evaluate(X_test,y_test)
print(accuracy[1])

63/63 [==============================] - 0s 5ms/step - loss: 0.1778 - accuracy: 0.9730
0.9729999899864197


## Show wrong prediction results
Observing wrong prediction result may help you improve your prediction.

<font color="red">**[ TODO ]**</font> show the wrong prediction results like this: 

<img src="https://imgur.com/BOTMyZH.jpg" width=30%><br>

- [Python | Get key from value in Dictionary](https://www.geeksforgeeks.org/python-get-key-from-value-in-dictionary/)

In [15]:
key_list = list(tok.word_index.keys())
value_list = list(tok.word_index.values())
result_ngram = []   # X_test 的 ngram, 也就是原來的sentence

# Return text from word vector
for i in range(len(X_test)):
    result_sublist = []
    X_test_sublist = list(X_test[i])
    for j in range(len(X_test_sublist)):
        if X_test_sublist[j] == 0:
            break
        else:
            position = value_list.index(X_test_sublist[j])
            result_sublist.append(key_list[position])
    
    result_ngram.append(" ".join(result_sublist))


- [Python numpy.argmax()](https://www.delftstack.com/zh-tw/api/numpy/python-numpy-argmax/)

In [16]:
# 每一列為預測為 0 or 1 的機率，因此我們取較高者為最後的預測結果

y_predict = np.argmax(model.predict(X_test), axis=1)
y_test_1= np.argmax(y_test, axis = 1)

In [17]:
result = pd.DataFrame()

result['ngram'] = result_ngram
result['label'] = y_test_1
result['predict'] = y_predict

In [18]:
result

ngram  label  predict
0        degree earn 62 percent      0        0
1           earn maybe 30 or 50      0        0
2        earn the kind of money      1        1
3            earn his 14th save      1        1
4         earn a smaller amount      1        1
...                         ...    ...      ...
1995       earn many times that      1        1
1996            earn such money      1        1
1997  earn free gear with bonus      1        1
1998        way to earn profits      0        0
1999         right you 'll earn      1        1

[2000 rows x 3 columns]

In [19]:
result[result['label'] != result['predict']]

ngram  label  predict
157                      right to try to earn      1        0
197                  earn your masters degree      0        1
264                          earn ones living      1        0
301                      earn its 70 interest      1        0
422                          earn and keep it      1        0
519                             earn a living      1        0
567                           earn big profit      1        0
641                      earn your commission      0        1
643                           earn real money      1        0
696                    earn some pocket money      1        0
724                             earn a living      1        0
741                     earn affiliate income      0        1
770                             more you earn      0        1
831                          earn their money      1        0
867   earn pension entitlements enabling them      1        0
897                        earn a 3 0 victory      1        0
948                       earn the gold award      0        1
949                         earn you a living      1        0
986                              more we earn      1        0
1021                              earn income      1        0
1054                       what they can earn      0        1
1081                          earn on average      0        1
1135                earn copyright protection      0        1
1175                        earn or get money      1        0
1201                    earn money earn money      1        0
1245                              what i earn      0        1
1248                   earn immediately money      1        0
1287             earn money online earn money      1        0
1339                                earn spot      1        0
1353               earn an independent income      1        0
1363                     earn a share of that      1        0
1420                        earn their profit      1        0
1427                           earn an income      1        0
1449                      earn another income      1        0
1462                     more productive earn      1        0
1463                         earn and to save      1        0
1470                       earn earned income      1        0
1501                              him to earn      1        0
1512                earn free gear with bonus      0        1
1526             million people who earn less      0        1
1536                               earn money      1        0
1585                    earn money earn money      1        0
1588                      earn yet more money      1        0
1612                         them try to earn      1        0
1622                        earn their credit      1        0
1629                 earn extra money genuine      0        1
1696                 earn to qualify for what      1        0
1719                                earn more      1        0
1721                              earn profit      1        0
1795                            earn the most      1        0
1808                               money earn      0        1
1912                          earn fake money      1        0
1917                     earn the same profit      1        0
1951            clear advantage and earn more      0        1

## TA's Notes

If you complete the Assignment, please use [this link](https://docs.google.com/spreadsheets/d/1QGeYl5dsD9sFO9SYg4DIKk-xr-yGjRDOOLKZqCLDv2E/edit#gid=807282025) to reserve demo time.  
The score is only given after TAs review your implementation, so <u>**make sure you make a appointment with a TA before you miss the deadline**</u> .  <br>After demo, please upload your assignment to eeclass. You just need to hand in this ipynb file and rename it as XXXXXXXXX(Your student ID).ipynb.
<br>Note that **late submission will not be allowed**.

## Learning Resource
[Deep Learning with Python](https://tanthiamhuat.files.wordpress.com/2018/03/deeplearningwithpython.pdf)

[Classification on IMDB](https://keras.io/examples/nlp/bidirectional_lstm_imdb/)